import { AtypDisplay, AtypText } from "@/fonts/fonts";
import "../styles/global.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${AtypDisplay.variable} ${AtypText.variable}`}>
      <body>{children}</body>
    </html>
  );
}
